@echo off
echo Installing dependencies...
npm install

echo Installing Firebase...
npm install firebase@10.12.1

echo Installing Remixicon...
npm install remixicon@4.2.0

echo Starting development server...
npm run serve
